/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedDrillRouteImport } from './routes/_authenticated.drill'
import { Route as AuthenticatedSrsSummaryRouteImport } from './routes/_authenticated.srs.summary'
import { Route as AuthenticatedSrsRunRouteImport } from './routes/_authenticated.srs.run'
import { Route as AuthenticatedQuizSummaryRouteImport } from './routes/_authenticated.quiz.summary'
import { Route as AuthenticatedQuizSetupRouteImport } from './routes/_authenticated.quiz.setup'
import { Route as AuthenticatedQuizRunRouteImport } from './routes/_authenticated.quiz.run'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDrillRoute = AuthenticatedDrillRouteImport.update({
  id: '/drill',
  path: '/drill',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSrsSummaryRoute = AuthenticatedSrsSummaryRouteImport.update({
  id: '/srs/summary',
  path: '/srs/summary',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSrsRunRoute = AuthenticatedSrsRunRouteImport.update({
  id: '/srs/run',
  path: '/srs/run',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuizSummaryRoute =
  AuthenticatedQuizSummaryRouteImport.update({
    id: '/quiz/summary',
    path: '/quiz/summary',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuizSetupRoute = AuthenticatedQuizSetupRouteImport.update({
  id: '/quiz/setup',
  path: '/quiz/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuizRunRoute = AuthenticatedQuizRunRouteImport.update({
  id: '/quiz/run',
  path: '/quiz/run',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/drill': typeof AuthenticatedDrillRoute
  '/quiz/run': typeof AuthenticatedQuizRunRoute
  '/quiz/setup': typeof AuthenticatedQuizSetupRoute
  '/quiz/summary': typeof AuthenticatedQuizSummaryRoute
  '/srs/run': typeof AuthenticatedSrsRunRoute
  '/srs/summary': typeof AuthenticatedSrsSummaryRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/drill': typeof AuthenticatedDrillRoute
  '/': typeof AuthenticatedIndexRoute
  '/quiz/run': typeof AuthenticatedQuizRunRoute
  '/quiz/setup': typeof AuthenticatedQuizSetupRoute
  '/quiz/summary': typeof AuthenticatedQuizSummaryRoute
  '/srs/run': typeof AuthenticatedSrsRunRoute
  '/srs/summary': typeof AuthenticatedSrsSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/drill': typeof AuthenticatedDrillRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/quiz/run': typeof AuthenticatedQuizRunRoute
  '/_authenticated/quiz/setup': typeof AuthenticatedQuizSetupRoute
  '/_authenticated/quiz/summary': typeof AuthenticatedQuizSummaryRoute
  '/_authenticated/srs/run': typeof AuthenticatedSrsRunRoute
  '/_authenticated/srs/summary': typeof AuthenticatedSrsSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/drill'
    | '/quiz/run'
    | '/quiz/setup'
    | '/quiz/summary'
    | '/srs/run'
    | '/srs/summary'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/drill'
    | '/'
    | '/quiz/run'
    | '/quiz/setup'
    | '/quiz/summary'
    | '/srs/run'
    | '/srs/summary'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/drill'
    | '/_authenticated/'
    | '/_authenticated/quiz/run'
    | '/_authenticated/quiz/setup'
    | '/_authenticated/quiz/summary'
    | '/_authenticated/srs/run'
    | '/_authenticated/srs/summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drill': {
      id: '/_authenticated/drill'
      path: '/drill'
      fullPath: '/drill'
      preLoaderRoute: typeof AuthenticatedDrillRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/srs/summary': {
      id: '/_authenticated/srs/summary'
      path: '/srs/summary'
      fullPath: '/srs/summary'
      preLoaderRoute: typeof AuthenticatedSrsSummaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/srs/run': {
      id: '/_authenticated/srs/run'
      path: '/srs/run'
      fullPath: '/srs/run'
      preLoaderRoute: typeof AuthenticatedSrsRunRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quiz/summary': {
      id: '/_authenticated/quiz/summary'
      path: '/quiz/summary'
      fullPath: '/quiz/summary'
      preLoaderRoute: typeof AuthenticatedQuizSummaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quiz/setup': {
      id: '/_authenticated/quiz/setup'
      path: '/quiz/setup'
      fullPath: '/quiz/setup'
      preLoaderRoute: typeof AuthenticatedQuizSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quiz/run': {
      id: '/_authenticated/quiz/run'
      path: '/quiz/run'
      fullPath: '/quiz/run'
      preLoaderRoute: typeof AuthenticatedQuizRunRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDrillRoute: typeof AuthenticatedDrillRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedQuizRunRoute: typeof AuthenticatedQuizRunRoute
  AuthenticatedQuizSetupRoute: typeof AuthenticatedQuizSetupRoute
  AuthenticatedQuizSummaryRoute: typeof AuthenticatedQuizSummaryRoute
  AuthenticatedSrsRunRoute: typeof AuthenticatedSrsRunRoute
  AuthenticatedSrsSummaryRoute: typeof AuthenticatedSrsSummaryRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDrillRoute: AuthenticatedDrillRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedQuizRunRoute: AuthenticatedQuizRunRoute,
  AuthenticatedQuizSetupRoute: AuthenticatedQuizSetupRoute,
  AuthenticatedQuizSummaryRoute: AuthenticatedQuizSummaryRoute,
  AuthenticatedSrsRunRoute: AuthenticatedSrsRunRoute,
  AuthenticatedSrsSummaryRoute: AuthenticatedSrsSummaryRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
