/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedEditorRouteImport } from './routes/_authenticated.editor'
import { Route as AuthenticatedDrillRouteImport } from './routes/_authenticated.drill'
import { Route as AuthenticatedEditorIndexRouteImport } from './routes/_authenticated.editor.index'
import { Route as AuthenticatedSrsSummaryRouteImport } from './routes/_authenticated.srs.summary'
import { Route as AuthenticatedSrsRunRouteImport } from './routes/_authenticated.srs.run'
import { Route as AuthenticatedQuizSummaryRouteImport } from './routes/_authenticated.quiz.summary'
import { Route as AuthenticatedQuizSetupRouteImport } from './routes/_authenticated.quiz.setup'
import { Route as AuthenticatedQuizRunRouteImport } from './routes/_authenticated.quiz.run'
import { Route as AuthenticatedEditorNewRouteImport } from './routes/_authenticated.editor.new'
import { Route as AuthenticatedEditorImportRouteImport } from './routes/_authenticated.editor.import'
import { Route as AuthenticatedEditorIdRouteImport } from './routes/_authenticated.editor.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEditorRoute = AuthenticatedEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDrillRoute = AuthenticatedDrillRouteImport.update({
  id: '/drill',
  path: '/drill',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEditorIndexRoute =
  AuthenticatedEditorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEditorRoute,
  } as any)
const AuthenticatedSrsSummaryRoute = AuthenticatedSrsSummaryRouteImport.update({
  id: '/srs/summary',
  path: '/srs/summary',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSrsRunRoute = AuthenticatedSrsRunRouteImport.update({
  id: '/srs/run',
  path: '/srs/run',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuizSummaryRoute =
  AuthenticatedQuizSummaryRouteImport.update({
    id: '/quiz/summary',
    path: '/quiz/summary',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQuizSetupRoute = AuthenticatedQuizSetupRouteImport.update({
  id: '/quiz/setup',
  path: '/quiz/setup',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedQuizRunRoute = AuthenticatedQuizRunRouteImport.update({
  id: '/quiz/run',
  path: '/quiz/run',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEditorNewRoute = AuthenticatedEditorNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedEditorRoute,
} as any)
const AuthenticatedEditorImportRoute =
  AuthenticatedEditorImportRouteImport.update({
    id: '/import',
    path: '/import',
    getParentRoute: () => AuthenticatedEditorRoute,
  } as any)
const AuthenticatedEditorIdRoute = AuthenticatedEditorIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedEditorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/drill': typeof AuthenticatedDrillRoute
  '/editor': typeof AuthenticatedEditorRouteWithChildren
  '/editor/$id': typeof AuthenticatedEditorIdRoute
  '/editor/import': typeof AuthenticatedEditorImportRoute
  '/editor/new': typeof AuthenticatedEditorNewRoute
  '/quiz/run': typeof AuthenticatedQuizRunRoute
  '/quiz/setup': typeof AuthenticatedQuizSetupRoute
  '/quiz/summary': typeof AuthenticatedQuizSummaryRoute
  '/srs/run': typeof AuthenticatedSrsRunRoute
  '/srs/summary': typeof AuthenticatedSrsSummaryRoute
  '/editor/': typeof AuthenticatedEditorIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/drill': typeof AuthenticatedDrillRoute
  '/': typeof AuthenticatedIndexRoute
  '/editor/$id': typeof AuthenticatedEditorIdRoute
  '/editor/import': typeof AuthenticatedEditorImportRoute
  '/editor/new': typeof AuthenticatedEditorNewRoute
  '/quiz/run': typeof AuthenticatedQuizRunRoute
  '/quiz/setup': typeof AuthenticatedQuizSetupRoute
  '/quiz/summary': typeof AuthenticatedQuizSummaryRoute
  '/srs/run': typeof AuthenticatedSrsRunRoute
  '/srs/summary': typeof AuthenticatedSrsSummaryRoute
  '/editor': typeof AuthenticatedEditorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/drill': typeof AuthenticatedDrillRoute
  '/_authenticated/editor': typeof AuthenticatedEditorRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/editor/$id': typeof AuthenticatedEditorIdRoute
  '/_authenticated/editor/import': typeof AuthenticatedEditorImportRoute
  '/_authenticated/editor/new': typeof AuthenticatedEditorNewRoute
  '/_authenticated/quiz/run': typeof AuthenticatedQuizRunRoute
  '/_authenticated/quiz/setup': typeof AuthenticatedQuizSetupRoute
  '/_authenticated/quiz/summary': typeof AuthenticatedQuizSummaryRoute
  '/_authenticated/srs/run': typeof AuthenticatedSrsRunRoute
  '/_authenticated/srs/summary': typeof AuthenticatedSrsSummaryRoute
  '/_authenticated/editor/': typeof AuthenticatedEditorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/drill'
    | '/editor'
    | '/editor/$id'
    | '/editor/import'
    | '/editor/new'
    | '/quiz/run'
    | '/quiz/setup'
    | '/quiz/summary'
    | '/srs/run'
    | '/srs/summary'
    | '/editor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/drill'
    | '/'
    | '/editor/$id'
    | '/editor/import'
    | '/editor/new'
    | '/quiz/run'
    | '/quiz/setup'
    | '/quiz/summary'
    | '/srs/run'
    | '/srs/summary'
    | '/editor'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/drill'
    | '/_authenticated/editor'
    | '/_authenticated/'
    | '/_authenticated/editor/$id'
    | '/_authenticated/editor/import'
    | '/_authenticated/editor/new'
    | '/_authenticated/quiz/run'
    | '/_authenticated/quiz/setup'
    | '/_authenticated/quiz/summary'
    | '/_authenticated/srs/run'
    | '/_authenticated/srs/summary'
    | '/_authenticated/editor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/editor': {
      id: '/_authenticated/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AuthenticatedEditorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/drill': {
      id: '/_authenticated/drill'
      path: '/drill'
      fullPath: '/drill'
      preLoaderRoute: typeof AuthenticatedDrillRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/editor/': {
      id: '/_authenticated/editor/'
      path: '/'
      fullPath: '/editor/'
      preLoaderRoute: typeof AuthenticatedEditorIndexRouteImport
      parentRoute: typeof AuthenticatedEditorRoute
    }
    '/_authenticated/srs/summary': {
      id: '/_authenticated/srs/summary'
      path: '/srs/summary'
      fullPath: '/srs/summary'
      preLoaderRoute: typeof AuthenticatedSrsSummaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/srs/run': {
      id: '/_authenticated/srs/run'
      path: '/srs/run'
      fullPath: '/srs/run'
      preLoaderRoute: typeof AuthenticatedSrsRunRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quiz/summary': {
      id: '/_authenticated/quiz/summary'
      path: '/quiz/summary'
      fullPath: '/quiz/summary'
      preLoaderRoute: typeof AuthenticatedQuizSummaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quiz/setup': {
      id: '/_authenticated/quiz/setup'
      path: '/quiz/setup'
      fullPath: '/quiz/setup'
      preLoaderRoute: typeof AuthenticatedQuizSetupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/quiz/run': {
      id: '/_authenticated/quiz/run'
      path: '/quiz/run'
      fullPath: '/quiz/run'
      preLoaderRoute: typeof AuthenticatedQuizRunRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/editor/new': {
      id: '/_authenticated/editor/new'
      path: '/new'
      fullPath: '/editor/new'
      preLoaderRoute: typeof AuthenticatedEditorNewRouteImport
      parentRoute: typeof AuthenticatedEditorRoute
    }
    '/_authenticated/editor/import': {
      id: '/_authenticated/editor/import'
      path: '/import'
      fullPath: '/editor/import'
      preLoaderRoute: typeof AuthenticatedEditorImportRouteImport
      parentRoute: typeof AuthenticatedEditorRoute
    }
    '/_authenticated/editor/$id': {
      id: '/_authenticated/editor/$id'
      path: '/$id'
      fullPath: '/editor/$id'
      preLoaderRoute: typeof AuthenticatedEditorIdRouteImport
      parentRoute: typeof AuthenticatedEditorRoute
    }
  }
}

interface AuthenticatedEditorRouteChildren {
  AuthenticatedEditorIdRoute: typeof AuthenticatedEditorIdRoute
  AuthenticatedEditorImportRoute: typeof AuthenticatedEditorImportRoute
  AuthenticatedEditorNewRoute: typeof AuthenticatedEditorNewRoute
  AuthenticatedEditorIndexRoute: typeof AuthenticatedEditorIndexRoute
}

const AuthenticatedEditorRouteChildren: AuthenticatedEditorRouteChildren = {
  AuthenticatedEditorIdRoute: AuthenticatedEditorIdRoute,
  AuthenticatedEditorImportRoute: AuthenticatedEditorImportRoute,
  AuthenticatedEditorNewRoute: AuthenticatedEditorNewRoute,
  AuthenticatedEditorIndexRoute: AuthenticatedEditorIndexRoute,
}

const AuthenticatedEditorRouteWithChildren =
  AuthenticatedEditorRoute._addFileChildren(AuthenticatedEditorRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedDrillRoute: typeof AuthenticatedDrillRoute
  AuthenticatedEditorRoute: typeof AuthenticatedEditorRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedQuizRunRoute: typeof AuthenticatedQuizRunRoute
  AuthenticatedQuizSetupRoute: typeof AuthenticatedQuizSetupRoute
  AuthenticatedQuizSummaryRoute: typeof AuthenticatedQuizSummaryRoute
  AuthenticatedSrsRunRoute: typeof AuthenticatedSrsRunRoute
  AuthenticatedSrsSummaryRoute: typeof AuthenticatedSrsSummaryRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDrillRoute: AuthenticatedDrillRoute,
  AuthenticatedEditorRoute: AuthenticatedEditorRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedQuizRunRoute: AuthenticatedQuizRunRoute,
  AuthenticatedQuizSetupRoute: AuthenticatedQuizSetupRoute,
  AuthenticatedQuizSummaryRoute: AuthenticatedQuizSummaryRoute,
  AuthenticatedSrsRunRoute: AuthenticatedSrsRunRoute,
  AuthenticatedSrsSummaryRoute: AuthenticatedSrsSummaryRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
